//
//  AmigaOS C++ wrapper
//
//  (c) 2024 TDolphin
//

#include "Utils.hpp"

#include "ValueTypes/ManufacturerID.hpp"

#include <map>

namespace AOS::Expansion
{
    // values/names taken from https://wiki.amigaos.net/wiki/Amiga_Hardware_Manufacturer_ID_Registry
    std::map<ManufacturerID, std::string> manufacturer2Name {
        { ManufacturerID::Micronik_0, "Micronik" },
        { ManufacturerID::PacificPeripherals_Profex, "Pacific Peripherals/Profex" },
        { ManufacturerID::KupkeComputertechnikGmbH_0, "Kupke Computertechnik GmbH" },
        { ManufacturerID::Memphis, "Memphis" },
        { ManufacturerID::_3_StateComputertechnik, "3-State Computertechnik" },
        { ManufacturerID::Commodore_Braunschweig, "Commodore (Braunschweig)" },
        { ManufacturerID::Commodore_WestChester_0, "Commodore (West Chester)" },
        { ManufacturerID::Commodore_WestChester_1, "Commodore (West Chester)" },
        { ManufacturerID::ProgressivePeripherals_Software_0, "Progressive Peripherals & Software" },
        { ManufacturerID::KolffComputerSupplies, "Kolff Computer Supplies" },
        { ManufacturerID::Tecmar, "Tecmar" },
        { ManufacturerID::Telesys, "Telesys" },
        { ManufacturerID::TheMicro_Forge, "The Micro-Forge" },
        { ManufacturerID::Kronos_CLtd_0, "Kronos/C Ltd." },
        { ManufacturerID::A_Squared, "A-Squared" },
        { ManufacturerID::ComspecCommunications, "Comspec Communications" },
        { ManufacturerID::HTElectronics, "HT Electronics" },
        { ManufacturerID::RDSSoftware, "RDS Software" },
        { ManufacturerID::AnakinResearch, "Anakin Research" },
        { ManufacturerID::MicroBotics, "MicroBotics" },
        { ManufacturerID::BobKrauth, "Bob Krauth" },
        { ManufacturerID::AccessAssociates_Alegra, "Access Associates (Alegra)" },
        { ManufacturerID::MiniCompSystemsLtd, "Mini Comp Systems Ltd." },
        { ManufacturerID::CypressTechnology, "Cypress Technology" },
        { ManufacturerID::FullerComputers, "Fuller Computers" },
        { ManufacturerID::GalaxyComputers, "Galaxy Computers" },
        { ManufacturerID::ADAResearch, "ADA Research" },
        { ManufacturerID::ComputerServiceItalia, "Computer Service Italia" },
        { ManufacturerID::Amigo, "Amigo" },
        { ManufacturerID::Micro_SolutionsInc, "Micro-Solutions Inc." },
        { ManufacturerID::StacarInternational, "Stacar International" },
        { ManufacturerID::VideoPrecisions, "Video Precisions" },
        { ManufacturerID::ASDGInc, "ASDG, Inc." },
        { ManufacturerID::IngBueroKalawsky, "Ing. Buero Kalawsky" },
        { ManufacturerID::ComputerTuning, "Computer Tuning" },
        { ManufacturerID::InterplanUnternehmensberatung, "Interplan Unternehmensberatung" },
        { ManufacturerID::Imtronics_Memphis_0, "Imtronics/Memphis" },
        { ManufacturerID::Commodore_LowellUniversity, "Commodore (Lowell University)" },
        { ManufacturerID::DesignLabs, "Design Labs" },
        { ManufacturerID::MCS, "MCS" },
        { ManufacturerID::BJFreeman, "B. J. Freeman" },
        { ManufacturerID::SideEffectsInc, "Side Effects Inc." },
        { ManufacturerID::OklahomaPersonalComp, "Oklahoma Personal Comp." },
        { ManufacturerID::AdvancedMicroInnovations, "Advanced Micro Innovations" },
        { ManufacturerID::IndustrialSupportServices, "Industrial Support Services" },
        { ManufacturerID::Technisoft, "Technisoft" },
        { ManufacturerID::ProlificInc, "Prolific, Inc." },
        { ManufacturerID::SofteamInc, "Softeam, Inc." },
        { ManufacturerID::GRCElectronics, "GRC Electronics" },
        { ManufacturerID::DavidLai, "David Lai" },
        { ManufacturerID::AmeristarTechnologies, "Ameristar Technologies" },
        { ManufacturerID::ClineRefrigeration, "Cline Refrigeration" },
        { ManufacturerID::CardiacPacemakersInc, "Cardiac Pacemakers, Inc." },
        { ManufacturerID::SupraCorp_CreativeMicrosystems, "Supra Corp. (Creative Microsystems)" },
        { ManufacturerID::WayneDiener, "Wayne Diener" },
        { ManufacturerID::ComputerSystemsAssociates_CSA, "Computer Systems Associates (CSA)" },
        { ManufacturerID::TrionixInc, "Trionix, Inc." },
        { ManufacturerID::DavidLucas, "David Lucas" },
        { ManufacturerID::AnalogPrecision, "Analog Precision" },
        { ManufacturerID::RBMDigitaltechnik, "RBM Digitaltechnik" },
        { ManufacturerID::M_TECHardwareDesign_0, "M-TEC Hardware Design" },
        { ManufacturerID::ThomasStenzel_DaFR34K, "Thomas Stenzel (DaFR34K)" },
        { ManufacturerID::BorisKrizma, "Boris Križma" },
        { ManufacturerID::GreatValleyProducts_0, "Great Valley Products" },
        { ManufacturerID::UAEAmigaEmulator, "UAE Amiga Emulator" },
        { ManufacturerID::MimeticsCorp, "Mimetics Corp." },
        { ManufacturerID::ACDA, "ACDA" },
        { ManufacturerID::FinnRJacobsen, "Finn R. Jacobsen" },
        { ManufacturerID::ElthenElectronics, "Elthen Electronics" },
        { ManufacturerID::NineTilesComputerSystemsLtd, "Nine Tiles Computer Systems Ltd." },
        { ManufacturerID::AnalogElectronics, "Analog Electronics" },
        { ManufacturerID::Bell_Howell, "Bell & Howell" },
        { ManufacturerID::RolandKochler, "Roland Kochler" },
        { ManufacturerID::ByteCorp, "Byte Corp." },
        { ManufacturerID::Reserved, "Reserved" },
        { ManufacturerID::DKBInc, "DKB, Inc." },
        { ManufacturerID::PacificPeripherals, "Pacific Peripherals" },
        { ManufacturerID::SysaphusSoftware, "Sysaphus Software" },
        { ManufacturerID::Digitronics, "Digitronics" },
        { ManufacturerID::AkronSystems, "Akron Systems" },
        { ManufacturerID::GreatValleyProducts_1, "Great Valley Products" },
        { ManufacturerID::Calmos, "Calmos" },
        { ManufacturerID::DoverResearch, "Dover Research" },
        { ManufacturerID::DavidKrehbiel, "David Krehbiel" },
        { ManufacturerID::SynergyPeripheralSystems, "Synergy Peripheral Systems" },
        { ManufacturerID::Xetec, "Xetec" },
        { ManufacturerID::MicronTechnology, "Micron Technology" },
        { ManufacturerID::CHElectronics, "CH Electronics" },
        { ManufacturerID::AmericanLiquidLight_0, "American Liquid Light" },
        { ManufacturerID::ProgressivePeripherals_Software_1, "Progressive Peripherals & Software" },
        { ManufacturerID::WicatSystems, "Wicat Systems" },
        { ManufacturerID::AppliedSystems_Peripherals, "Applied Systems & Peripherals" },
        { ManufacturerID::DelawareValleySoftware, "Delaware Valley Software" },
        { ManufacturerID::Palomax, "Palomax" },
        { ManufacturerID::IncognitoSoftware, "Incognito Software" },
        { ManufacturerID::Jadesign, "Jadesign" },
        { ManufacturerID::BVR, "BVR" },
        { ManufacturerID::SpiritTechnology_0, "Spirit Technology" },
        { ManufacturerID::SpiritTechnology_1, "Spirit Technology" },
        { ManufacturerID::Atronic, "Atronic" },
        { ManufacturerID::ScottKarlin, "Scott Karlin" },
        { ManufacturerID::Howitch, "Howitch" },
        { ManufacturerID::SullivanBrothersVisualEngineers, "Sullivan Brothers Visual Engineers" },
        { ManufacturerID::GIT, "G I T" },
        { ManufacturerID::AmigoBusinessComputers, "Amigo Business Computers" },
        { ManufacturerID::MicroEAb, "Micro E Ab" },
        { ManufacturerID::RalphKruse, "Ralph Kruse" },
        { ManufacturerID::ClearpointResearch, "Clearpoint Research" },
        { ManufacturerID::Kodiak, "Kodiak" },
        { ManufacturerID::BSC_0, "BSC" },
        { ManufacturerID::NoNameShown, "No Name Shown" },
        { ManufacturerID::CommodoreBraunschweig, "Commodore Braunschweig" },
        { ManufacturerID::BSC_1, "BSC" },
        { ManufacturerID::Kronos_CLtd_1, "Kronos/C Ltd." },
        { ManufacturerID::Spartanics, "Spartanics" },
        { ManufacturerID::JochheimComputerTuning, "Jochheim Computer Tuning" },
        { ManufacturerID::TransDataSystems, "Trans Data Systems" },
        { ManufacturerID::AppliedSystems_PeripheralsLtd, "Applied Systems & Peripherals Ltd." },
        { ManufacturerID::CheckpointTechnologies, "Checkpoint Technologies" },
        { ManufacturerID::AdeptDevelopment_0, "Adept Development" },
        { ManufacturerID::AdvancedComputerDesign, "Advanced Computer Design" },
        { ManufacturerID::SirNetics, "Sir Netics" },
        { ManufacturerID::ExpertServices, "Expert Services" },
        { ManufacturerID::DigitalArtSystems, "Digital Art Systems" },
        { ManufacturerID::AdeptDevelopment_1, "Adept Development" },
        { ManufacturerID::ExpansionTechnologies_ExpansionSystems, "Expansion Technologies (Expansion Systems)" },
        { ManufacturerID::Alphatech, "Alphatech" },
        { ManufacturerID::EdotronikGmbH, "Edotronik GmbH" },
        { ManufacturerID::CaliforniaAccess_Synergy, "California Access/Synergy" },
        { ManufacturerID::BowdenWilliamsFull_Assoc, "Bowden, Williams, Full & Assoc." },
        { ManufacturerID::NESInc, "NES, Inc." },
        { ManufacturerID::Amdev, "Amdev" },
        { ManufacturerID::BigBrotherSecuritySystems, "Big Brother Security Systems" },
        { ManufacturerID::ActiveCircuitsInc, "Active Circuits Inc." },
        { ManufacturerID::ICDInc, "ICD, Inc." },
        { ManufacturerID::Multi_MegElectronique, "Multi-Meg Electronique" },
        { ManufacturerID::KupkeComputertechnikGmbH_1, "Kupke Computertechnik GmbH" },
        { ManufacturerID::TheCheckeredBall, "The Checkered Ball" },
        { ManufacturerID::HiTensionComputerServicesLtd_UK, "Hi Tension Computer Services Ltd. (UK)" },
        { ManufacturerID::AlfaData, "Alfa Data" },
        { ManufacturerID::GreatValleyProducts_2, "Great Valley Products" },
        { ManufacturerID::Interworks, "Interworks" },
        { ManufacturerID::GalyshEnterprises, "Galysh Enterprises" },
        { ManufacturerID::HarditalSynthesis, "Hardital Synthesis" },
        { ManufacturerID::GBS, "GBS" },
        { ManufacturerID::CircumDesignInc, "Circum Design Inc." },
        { ManufacturerID::AlbertaMicroElectronicCenter, "Alberta Micro Electronic Center" },
        { ManufacturerID::Bestech, "Bestech" },
        { ManufacturerID::LasarFantasy, "Lasar Fantasy" },
        { ManufacturerID::Pulsar, "Pulsar" },
        { ManufacturerID::Ivis, "Ivis" },
        { ManufacturerID::AppliedEngineering, "Applied Engineering" },
        { ManufacturerID::Solid_StateDesign_Development, "Solid-State Design & Development" },
        { ManufacturerID::VisonQuest, "Vison Quest" },
        { ManufacturerID::SeaviewSoftware, "Seaview Software" },
        { ManufacturerID::BSC_2, "BSC" },
        { ManufacturerID::BerndCulenfeld, "Bernd Culenfeld" },
        { ManufacturerID::AmericanLiquidLight_1, "American Liquid Light" },
        { ManufacturerID::CEGITES, "CEGITES" },
        { ManufacturerID::QuadliteComputersLtd, "Quadlite Computers Ltd." },
        { ManufacturerID::SiliconPeace, "Silicon Peace" },
        { ManufacturerID::BlackBeltSystems, "Black Belt Systems" },
        { ManufacturerID::VillageTronic_0, "Village Tronic" },
        { ManufacturerID::ReadySoft_0, "ReadySoft" },
        { ManufacturerID::PhoenixMicroTechnologies, "Phoenix Micro Technologies" },
        { ManufacturerID::AdvancedSystems_Software, "Advanced Systems & Software" },
        { ManufacturerID::RomboProductions, "Rombo Productions" },
        { ManufacturerID::ImpulseInc, "Impulse Inc." },
        { ManufacturerID::BetaUnlimited, "Beta Unlimited" },
        { ManufacturerID::MemoryExpansionSystemLtd, "Memory Expansion System, Ltd." },
        { ManufacturerID::VortexComputerSystemsGmbH, "Vortex Computer Systems GmbH" },
        { ManufacturerID::PlatypusSystems, "Platypus Systems" },
        { ManufacturerID::GigatronOHG, "Gigatron OHG" },
        { ManufacturerID::PGElectronics, "PG Electronics" },
        { ManufacturerID::NewTechnologiesGroup, "New Technologies Group" },
        { ManufacturerID::InteractiveVideoSystems_IVS, "Interactive Video Systems (IVS)" },
        { ManufacturerID::Vector, "Vector" },
        { ManufacturerID::PacificDigital_0, "Pacific Digital" },
        { ManufacturerID::Xanadu, "Xanadu" },
        { ManufacturerID::PacificDigital_1, "Pacific Digital" },
        { ManufacturerID::X_Pert, "X-Pert" },
        { ManufacturerID::TheAmigaCentre, "The Amiga Centre" },
        { ManufacturerID::DigitalPacific, "Digital Pacific" },
        { ManufacturerID::SolidStateLeisure, "Solid State Leisure" },
        { ManufacturerID::HydraSystems, "Hydra Systems" },
        { ManufacturerID::Cumana, "Cumana" },
        { ManufacturerID::KAPS2CConception, "KAPS 2C Conception" },
        { ManufacturerID::MikeMason, "Mike Mason" },
        { ManufacturerID::ForYourEyes, "For Your Eyes" },
        { ManufacturerID::VolkmarBreitfeldComputersysteme, "Volkmar Breitfeld Computersysteme" },
        { ManufacturerID::SunrizeIndustries, "Sunrize Industries" },
        { ManufacturerID::ScottAdvancedMicroDesigns, "Scott Advanced Micro Designs" },
        { ManufacturerID::DigitalMicronics, "Digital Micronics" },
        { ManufacturerID::Alfa_Laval, "Alfa-Laval" },
        { ManufacturerID::MultigrosA_S, "Multigros A/S" },
        { ManufacturerID::Archos, "Archos" },
        { ManufacturerID::IcomSimulations, "Icom Simulations" },
        { ManufacturerID::CommodoreTestEngineeringGroup, "Commodore Test Engineering Group" },
        { ManufacturerID::Microcreations, "Microcreations" },
        { ManufacturerID::ShoestringProductions, "Shoestring Productions" },
        { ManufacturerID::Faberushi, "Faberushi" },
        { ManufacturerID::EveshamMicroLtd, "Evesham Micro Ltd." },
        { ManufacturerID::PanagolinLaserSoftware, "Panagolin Laser Software" },
        { ManufacturerID::ThomasRudloff, "Thomas Rudloff" },
        { ManufacturerID::DanielHohabir, "Daniel Hohabir" },
        { ManufacturerID::GfxBaseInc, "GfxBase, Inc." },
        { ManufacturerID::Axellabs, "Axellabs" },
        { ManufacturerID::RoctecElectronicsInc, "Roctec Electronics Inc." },
        { ManufacturerID::OmegaDatentechnik, "Omega Datentechnik" },
        { ManufacturerID::Atlantis, "Atlantis" },
        { ManufacturerID::SkytecComputers, "Skytec Computers" },
        { ManufacturerID::ProtarElectronics, "Protar Electronics" },
        { ManufacturerID::ACS, "ACS" },
        { ManufacturerID::SoftwareResultsEnterprises, "Software Results Enterprises" },
        { ManufacturerID::InfinitySystemsDesignGroup, "Infinity Systems Design Group" },
        { ManufacturerID::TradeIt, "Trade It" },
        { ManufacturerID::SuntecInc, "Suntec, Inc." },
        { ManufacturerID::DJWMicroSystems, "DJW Micro Systems" },
        { ManufacturerID::PowerComputingLtd, "Power Computing Ltd." },
        { ManufacturerID::MacroSystems_0, "MacroSystems" },
        { ManufacturerID::MasoboshiGmbH_DCE, "Masoboshi GmbH (DCE)" },
        { ManufacturerID::HALSoftwareHardwareHandel, "HAL Software Hardware Handel" },
        { ManufacturerID::MainhattanData, "Mainhattan Data" },
        { ManufacturerID::DigitalProcessingSystem_0, "Digital Processing System" },
        { ManufacturerID::BlueRibbonSoundworks, "Blue Ribbon Soundworks" },
        { ManufacturerID::XPert, "XPert" },
        { ManufacturerID::DelaComp, "DelaComp" },
        { ManufacturerID::SuperformanceComputerEngineeringGmbH, "Superformance Computer Engineering GmbH" },
        { ManufacturerID::OverlandEngineering, "Overland Engineering" },
        { ManufacturerID::ThomasHamren, "Thomas Hamren" },
        { ManufacturerID::VillageTronic_1, "Village Tronic" },
        { ManufacturerID::ToolboxDesign, "Toolbox Design" },
        { ManufacturerID::DigitalProcessingSystem_1, "Digital Processing System" },
        { ManufacturerID::Superformance, "Superformance" },
        { ManufacturerID::UtilitiesUnlimited, "Utilities Unlimited" },
        { ManufacturerID::phase5, "phase 5" },
        { ManufacturerID::JuergenKommos, "Juergen Kommos" },
        { ManufacturerID::ElectronicDesign_0, "Electronic Design" },
        { ManufacturerID::JamesCookUniversityofNorthQueensland, "James Cook University of North Queensland" },
        { ManufacturerID::AmiTrixDevelopment, "AmiTrix Development" },
        { ManufacturerID::Ferranti, "Ferranti" },
        { ManufacturerID::LeviathanDevelopment, "Leviathan Development" },
        { ManufacturerID::UnitedVideoInc, "United Video Inc." },
        { ManufacturerID::GPSoftPtyLtd, "GPSoft Pty. Ltd." },
        { ManufacturerID::ArMAX, "ArMAX" },
        { ManufacturerID::CPComputer, "CP Computer" },
        { ManufacturerID::AMOK_AmigaModule_OberonKlub, "AMOK - Amiga Module & Oberon Klub" },
        { ManufacturerID::ITEKNeser_SieberGbR, "ITEK Neser & Sieber GbR" },
        { ManufacturerID::PhillipCLello, "Phillip C. Lello" },
        { ManufacturerID::CyborgDesignServices, "Cyborg Design Services" },
        { ManufacturerID::G2Systems, "G2 Systems" },
        { ManufacturerID::ProSystemComputersysteme, "Pro System Computersysteme" },
        { ManufacturerID::ZEUSElectronic, "ZEUS Electronic" },
        { ManufacturerID::Altatech, "Altatech" },
        { ManufacturerID::NewTek, "NewTek" },
        { ManufacturerID::M_TECHardwareDesign_1, "M-TEC Hardware Design" },
        { ManufacturerID::GreatValleyProducts_3, "Great Valley Products" },
        { ManufacturerID::Amitek, "Amitek" },
        { ManufacturerID::IngenieurbueroHelfrich, "Ingenieurbuero Helfrich" },
        { ManufacturerID::TheNeoGroup, "The Neo Group" },
        { ManufacturerID::Cyon, "Cyon" },
        { ManufacturerID::BobResearchGroup, "Bob Research Group" },
        { ManufacturerID::RichmondSoundDesignLtd, "Richmond Sound Design Ltd." },
        { ManufacturerID::USCybernetics, "US Cybernetics" },
        { ManufacturerID::FulvioIeva, "Fulvio Ieva" },
        { ManufacturerID::SiliconStudio, "Silicon Studio" },
        { ManufacturerID::MacroSystems_USA, "MacroSystems (USA)" },
        { ManufacturerID::ConspectorEntertainment, "Conspector Entertainment" },
        { ManufacturerID::Laserforum, "Laserforum" },
        { ManufacturerID::ElboxComputer, "Elbox Computer" },
        { ManufacturerID::AppliedMagicInc, "Applied Magic Inc." },
        { ManufacturerID::SDLLtd, "SDL Ltd." },
        { ManufacturerID::Harms, "Harms" },
        { ManufacturerID::A1KorgCommunity, "A1K.org Community" },
        { ManufacturerID::Micronik_1, "Micronik" },
        { ManufacturerID::Team4, "Team 4" },
        { ManufacturerID::E3B, "E3B" },
        { ManufacturerID::Micronik_2, "Micronik" },
        { ManufacturerID::MegaMicro, "MegaMicro" },
        { ManufacturerID::DigiFeX, "DigiFeX" },
        { ManufacturerID::Imtronics_Memphis_1, "Imtronics/Memphis" },
        { ManufacturerID::PROTAR, "PROTAR" },
        { ManufacturerID::FrankStrauBElektronik, "Frank Strauß Elektronik" },
        { ManufacturerID::IndividualComputers, "Individual Computers" },
        { ManufacturerID::FleschHornemannComputerElec, "Flesch Hornemann Computer Elec." },
        { ManufacturerID::KupkeComputertechnikGmbH_2, "Kupke Computertechnik GmbH" },
        { ManufacturerID::RBMdigitaltechnik, "RBM digitaltechnik" },
        { ManufacturerID::MacroSystems_1, "MacroSystems" },
        { ManufacturerID::ITH, "ITH" },
        { ManufacturerID::VMC, "VMC" },
        { ManufacturerID::AmbienceCreationTechnology, "Ambience Creation Technology" },
        { ManufacturerID::CreativeDevelopment, "Creative Development" },
        { ManufacturerID::GeorgBraun, "Georg Braun" },
        { ManufacturerID::SwedishUserGroupofAmiga, "Swedish User Group of Amiga" },
        { ManufacturerID::JakubBednarski, "Jakub Bednarski" },
        { ManufacturerID::KryoFluxLtd, "KryoFlux, Ltd." },
        { ManufacturerID::IgorMajstorovic, "Igor Majstorovic / Apollo" },
        { ManufacturerID::AlastairMRobinson, "Alastair M. Robinson" },
        { ManufacturerID::AustexSoftware, "Austex Software" },
        { ManufacturerID::SorenGust, "Sören Gust" },
        { ManufacturerID::RokKrajnc, "Rok Krajnc" },
        { ManufacturerID::TimTashpulatov, "Tim Tashpulatov" },
        { ManufacturerID::_7_bit, "7-bit" },
        { ManufacturerID::SakuraIT, "Sakura IT" },
        { ManufacturerID::FPGAArcade, "FPGAArcade" },
        { ManufacturerID::CancerSoftInc, "CancerSoft Inc." },
        { ManufacturerID::StephenLeary, "Stephen Leary" },
        { ManufacturerID::DMASoftlabLLC, "DMA Softlab LLC" },
        { ManufacturerID::BrookhouseEngineering, "Brookhouse Engineering" },
        { ManufacturerID::EduardoArana, "Eduardo Arana" },
        { ManufacturerID::CS_LAB, "CS-LAB" },
        { ManufacturerID::RobertMiranda, "Robert Miranda" },
        { ManufacturerID::RastPort, "RastPort" },
        { ManufacturerID::UASInterfaceLtd6, "UAS Interface Ltd6" },
        { ManufacturerID::AmigaKit, "Amiga Kit" },
        { ManufacturerID::CentralTexasCommodoreUserGroup, "Central Texas Commodore User Group" },
        { ManufacturerID::ConfusionResearchCenter, "Confusion Research Center" },
        { ManufacturerID::SolarSoyuzZaibatsu, "Solar Soyuz Zaibatsu" },
        { ManufacturerID::InhouseInformation, "Inhouse Information" },
        { ManufacturerID::BioCon, "Bio Con" },
        { ManufacturerID::HK_Computer, "HK-Computer" },
        { ManufacturerID::Cloanto, "Cloanto" },
        { ManufacturerID::OliverGantert, "Oliver Gantert" },
        { ManufacturerID::RafalGabrielChyla, "Rafal Gabriel Chyla" },
        { ManufacturerID::Vortex, "Vortex" },
        { ManufacturerID::SpiritTechnology_3, "Spirit Technology" },
        { ManufacturerID::ExpansionSystems, "Expansion Systems" },
        { ManufacturerID::ReadySoft_1, "ReadySoft" },
        { ManufacturerID::Phase5DigitalProducts, "Phase 5 Digital Products" },
        { ManufacturerID::DigitalProcessingSystemsInc, "Digital Processing Systems Inc." },
        { ManufacturerID::ACTElektronik_0, "ACT Elektronik" },
        { ManufacturerID::ACTElektronik_1, "ACT Elektronik" },
        { ManufacturerID::TowerTechnologies, "Tower Technologies" },
        { ManufacturerID::ElectronicDesign_1, "Electronic Design" },
        { ManufacturerID::Media_net_Point, "Media-net-Point" },
        { ManufacturerID::Petsoff_Finland, "Petsoff, Finland" },
        { ManufacturerID::UweGerlach, "Uwe Gerlach" },
        { ManufacturerID::AteoConcepts, "Ateo Concepts" },
        { ManufacturerID::ALiENDESiGN, "ALiENDESiGN" },
        { ManufacturerID::ACT, "A.C.T." },
        { ManufacturerID::HK_Computer_ELSAT, "HK-Computer (ELSAT)" },
        { ManufacturerID::MacroSystems_Germany, "MacroSystems (Germany)" },
        { ManufacturerID::Markt_Technik_0, "Markt & Technik" },
        { ManufacturerID::Markt_Technik_1, "Markt & Technik" },
        { ManufacturerID::Combitec_0, "Combitec" },
        { ManufacturerID::Combitec_1, "Combitec" },
        { ManufacturerID::MNTMediaandTechnologyUG, "MNT Media and Technology UG" },
        { ManufacturerID::MAST, "M.A.S.T." },
        { ManufacturerID::AethreumDigital, "Aethreum Digital" },
        { ManufacturerID::Reis_Ware_0, "Reis-Ware" },
        { ManufacturerID::Cameron, "Cameron" },
        { ManufacturerID::Reis_Ware_1, "Reis-Ware" },
        { ManufacturerID::Matay, "Matay" },
        { ManufacturerID::Phoenix, "Phoenix" },
        { ManufacturerID::Combitec, "Combitec" },
        { ManufacturerID::ForefrontTechnologiesInc, "Forefront Technologies Inc." },
    };

    std::string Utils::GetManufacturerName(const ManufacturerID manufacturerID)
    {
        auto iter = manufacturer2Name.find(manufacturerID);
        return iter != manufacturer2Name.end() ? iter->second : "Unknown";
    }
}
