//
//  AmigaOS C++ wrapper
//
//  (c) 2024-2025 TDolphin
//

#pragma once

#ifdef __MORPHOS__
#include <exec/system.h>

namespace AOS::Exec
{
    enum class SYSTEMINFOTYPE : unsigned long
    {
        SYSTEM = SYSTEMINFOTYPE_SYSTEM, // returns the System family
        MACHINE = SYSTEMINFOTYPE_MACHINE,
        PPC_CPUVERSION = SYSTEMINFOTYPE_PPC_CPUVERSION,
        PPC_CPUREVISION = SYSTEMINFOTYPE_PPC_CPUREVISION,
        PPC_CPUCLOCK = SYSTEMINFOTYPE_PPC_CPUCLOCK,
        PPC_BUSCLOCK = SYSTEMINFOTYPE_PPC_BUSCLOCK,
        PPC_ICACHEL1SIZE = SYSTEMINFOTYPE_PPC_ICACHEL1SIZE,
        PPC_ICACHEL1LINES = SYSTEMINFOTYPE_PPC_ICACHEL1LINES,
        PPC_ICACHEL1LINESIZE = SYSTEMINFOTYPE_PPC_ICACHEL1LINESIZE,
        PPC_DCACHEL1SIZE = SYSTEMINFOTYPE_PPC_DCACHEL1SIZE,
        PPC_DCACHEL1LINES = SYSTEMINFOTYPE_PPC_DCACHEL1LINES,
        PPC_DCACHEL1LINESIZE = SYSTEMINFOTYPE_PPC_DCACHEL1LINESIZE,
        PPC_CACHEL1TYPE = SYSTEMINFOTYPE_PPC_CACHEL1TYPE,
        PPC_CACHEL1FLAGS = SYSTEMINFOTYPE_PPC_CACHEL1FLAGS,
        PPC_ICACHEL2SIZE = SYSTEMINFOTYPE_PPC_ICACHEL2SIZE,
        PPC_ICACHEL2LINES = SYSTEMINFOTYPE_PPC_ICACHEL2LINES,
        PPC_ICACHEL2LINESIZE = SYSTEMINFOTYPE_PPC_ICACHEL2LINESIZE,
        PPC_DCACHEL2SIZE = SYSTEMINFOTYPE_PPC_DCACHEL2SIZE,
        PPC_DCACHEL2LINES = SYSTEMINFOTYPE_PPC_DCACHEL2LINES,
        PPC_DCACHEL2LINESIZE = SYSTEMINFOTYPE_PPC_DCACHEL2LINESIZE,
        PPC_CACHEL2TYPE = SYSTEMINFOTYPE_PPC_CACHEL2TYPE,
        PPC_CACHEL2FLAGS = SYSTEMINFOTYPE_PPC_CACHEL2FLAGS,
        PPC_ICACHEL3SIZE = SYSTEMINFOTYPE_PPC_ICACHEL3SIZE,
        PPC_ICACHEL3LINES = SYSTEMINFOTYPE_PPC_ICACHEL3LINES,
        PPC_ICACHEL3LINESIZE = SYSTEMINFOTYPE_PPC_ICACHEL3LINESIZE,
        PPC_DCACHEL3SIZE = SYSTEMINFOTYPE_PPC_DCACHEL3SIZE,
        PPC_DCACHEL3LINES = SYSTEMINFOTYPE_PPC_DCACHEL3LINES,
        PPC_DCACHEL3LINESIZE = SYSTEMINFOTYPE_PPC_DCACHEL3LINESIZE,
        PPC_CACHEL3TYPE = SYSTEMINFOTYPE_PPC_CACHEL3TYPE,
        PPC_CACHEL3FLAGS = SYSTEMINFOTYPE_PPC_CACHEL3FLAGS,
        PPC_TLBENTRIES = SYSTEMINFOTYPE_PPC_TLBENTRIES,
        PPC_TLBSETS = SYSTEMINFOTYPE_PPC_TLBSETS,
        PPC_FPU = SYSTEMINFOTYPE_PPC_FPU, // PowerPC has a FPU
        PPC_ALTIVEC = SYSTEMINFOTYPE_PPC_ALTIVEC, // PowerPC has Altivec
        PPC_PERFMONITOR = SYSTEMINFOTYPE_PPC_PERFMONITOR, // PowerPC has performance measurement cpu extension
        PPC_DATASTREAM = SYSTEMINFOTYPE_PPC_DATASTREAM, // PowerPC has data stream support
        PPC_RESERVATIONSIZE = SYSTEMINFOTYPE_PPC_RESERVATIONSIZE, // PowerPC has reservation size support
        PPC_BUSTICKS = SYSTEMINFOTYPE_PPC_BUSTICKS, // PowerPC has bus tick support
        PPC_CPUTEMP = SYSTEMINFOTYPE_PPC_CPUTEMP, // CPU Temperature in 8.24 fixedpoint, degrees celsius
        PPC_DABR = SYSTEMINFOTYPE_PPC_DABR, // PowerPC has Data Address Breakpoint Register
        PAGESIZE = SYSTEMINFOTYPE_PAGESIZE, // Page size in bytes
        CPUCOUNT = SYSTEMINFOTYPE_CPUCOUNT, // Number of CPUs
        TBCLOCKFREQUENCY = SYSTEMINFOTYPE_TBCLOCKFREQUENCY, // Timer base clock frequency
        UPTIMETICKS = SYSTEMINFOTYPE_UPTIMETICKS, // Uptime in ticks
        LASTSECTICKS = SYSTEMINFOTYPE_LASTSECTICKS, // Last sector time in ticks
        RECENTTICKS = SYSTEMINFOTYPE_RECENTTICKS, // Recent time in ticks
        CPUTIME = SYSTEMINFOTYPE_CPUTIME, // CPU time in ticks
        LASTSECCPUTIME = SYSTEMINFOTYPE_LASTSECCPUTIME, // Last sector CPU time in ticks
        RECENTCPUTIME = SYSTEMINFOTYPE_RECENTCPUTIME, // Recent CPU time in ticks
        VOLUNTARYCSW = SYSTEMINFOTYPE_VOLUNTARYCSW, // Voluntary context switches
        INVOLUNTARYCSW = SYSTEMINFOTYPE_INVOLUNTARYCSW, // Involuntary context switches
        LASTSECVOLUNTARYCSW = SYSTEMINFOTYPE_LASTSECVOLUNTARYCSW, // Last sector voluntary context switches
        LASTSECINVOLUNTARYCSW = SYSTEMINFOTYPE_LASTSECINVOLUNTARYCSW, // Last sector involuntary context switches
        LOADAVG1 = SYSTEMINFOTYPE_LOADAVG1, // Load average 1
        LOADAVG2 = SYSTEMINFOTYPE_LOADAVG2, // Load average 2
        LOADAVG3 = SYSTEMINFOTYPE_LOADAVG3, // Load average 3
        TASKSCREATED = SYSTEMINFOTYPE_TASKSCREATED, // Tasks created
        TASKSFINISHED = SYSTEMINFOTYPE_TASKSFINISHED, // Tasks finished
        LAUNCHTIMETICKS = SYSTEMINFOTYPE_LAUNCHTIMETICKS, // Launch time in ticks
        LAUNCHTIMETICKS1978 = SYSTEMINFOTYPE_LAUNCHTIMETICKS1978, // Launch time in ticks (1978)
        TASKSRUNNING = SYSTEMINFOTYPE_TASKSRUNNING, // Tasks running
        TASKSSLEEPING = SYSTEMINFOTYPE_TASKSSLEEPING, // Tasks sleeping
        EMULHANDLESIZE = SYSTEMINFOTYPE_EMULHANDLESIZE,
        EXCEPTIONMSGPORT = SYSTEMINFOTYPE_EXCEPTIONMSGPORT,
        TASKEXITCODE = SYSTEMINFOTYPE_TASKEXITCODE,
        TASKEXITCODE_M68K = SYSTEMINFOTYPE_TASKEXITCODE_M68K,
        EMULATION_START = SYSTEMINFOTYPE_EMULATION_START,
        EMULATION_SIZE = SYSTEMINFOTYPE_EMULATION_SIZE,
        MODULE_START = SYSTEMINFOTYPE_MODULE_START,
        MODULE_SIZE = SYSTEMINFOTYPE_MODULE_SIZE,
        EXCEPTIONMSGPORT_68K = SYSTEMINFOTYPE_EXCEPTIONMSGPORT_68K,
        ALERTMSGPORT = SYSTEMINFOTYPE_ALERTMSGPORT,
        VENDOR = SYSTEMINFOTYPE_VENDOR,
        REVISION = SYSTEMINFOTYPE_REVISION,
        MAGIC1 = SYSTEMINFOTYPE_MAGIC1,
        MAGIC2 = SYSTEMINFOTYPE_MAGIC2,
        MAXHITCOUNT = SYSTEMINFOTYPE_MAXHITCOUNT,
        MAXALERTCOUNT = SYSTEMINFOTYPE_MAXALERTCOUNT,
        REGUSER = SYSTEMINFOTYPE_REGUSER,
        FREEBLOCKS = SYSTEMINFOTYPE_FREEBLOCKS,
        CPUNAME = SYSTEMINFOTYPE_CPUNAME,
        CPUFAMILYNAME = SYSTEMINFOTYPE_CPUFAMILYNAME,
        NEWSCHEDULER = SYSTEMINFOTYPE_NEWSCHEDULER,
    };
}

#endif // __MORPHOS__
